import = [
    "~/.config/alacritty/themes/themes/rose-pine-dawn.toml",
    # "~/.config/alacritty/themes/themes/pencil_light.toml",
    # "~/.config/alacritty/themes/themes/night_owlish_light.toml",
]

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "main"]


[font]
size = 16.0
normal.family = "Fira Code"

[scrolling]
history = 0

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "Q", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"


[window]
decorations = "none"
