
import = [
    "~/.config/alacritty/themes/themes/night_owlish_light.toml"
]

[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "main"]

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 16.0
normal.family = "Fira Code"
normal.style = "SemiBold"


[scrolling]
history = 0

[window]
decorations = "none"
