#!/bin/sh

export DISPLAY=:0
while true
do
  CHARGE=$(cat /sys/class/power_supply/BAT1/charge_now)
  ADAPTER=$(cat /sys/class/power_supply/ADP1/online)
  if (( $CHARGE < 400000 && $ADAPTER==0))
	then
		timeout 28s i3-nagbar -m "Low battery,please recharge!!" &
    #play a alert sound, slackware default
    play /usr/share/sounds/purple/alert.wav
    cd $Curr
	fi	
	sleep 50s
done

